version: '3.8'

services:
  # Backend service
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      # These environment variables will be used by Spring Boot
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=your_db_password
    depends_on:
      - db
    networks:
      - myapp-network

  # Database service (PostgreSQL)
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_db_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - myapp-network

  # Frontend service
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - myapp-network

# Networks to allow communication between services
networks:
  myapp-network:
    driver: bridge

# Volumes for persistent data storage
volumes:
  postgres-data: